version: '3.3'
services:
  rasa:
    image: rasa/rasa:3.1.2
    depends_on:
      - mongo
    ports:
      - 5005:5005
    volumes:
      - ./:/app:rw
    command:
      - run
  mongo:
    image: mongo:5.0.13
    container_name: inurge
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rasa
    ports:
      - 27017:27017
    volumes:
      - data_volume:/data/db:rw
volumes:
  data_volume: